### ISSUE TITLE
Kernel Restarting kats_101 at m.fit()

### ISSUE THREAD

**Issue by viktor-begun** [facebookresearch/Kats#221]
Hi, I try to go through kats_101 and at
 
2.1 An example with Prophet model
...
#fit model simply by calling m.fit()
m.fit()
...

I have this message: 

"Kernel Restarting
The kernel for Kats/tutorials/kats_101_basics.ipynb appears to have died. It will restart automatically."

Then the kernel dies.

The error is:

"
INFO:fbprophet:Disabling weekly seasonality. Run prophet with weekly_seasonality=True to override this.
INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
Error in sys.excepthook:
Traceback (most recent call last):
  File "C:\Users\begun\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 1979, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'KeyError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\begun\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 1981, in showtraceback
    stb = self.InteractiveTB.structured_traceback(etype,
  File "C:\Users\begun\Anaconda3\lib\site-packages\IPython\core\ultratb.py", line 1105, in structured_traceback
    return FormattedTB.structured_traceback(
  File "C:\Users\begun\Anaconda3\lib\site-packages\IPython\core\ultratb.py", line 999, in structured_traceback
    return VerboseTB.structured_traceback(
  File "C:\Users\begun\Anaconda3\lib\site-packages\IPython\core\ultratb.py", line 851, in structured_traceback
    assert etb is not None
AssertionError

Original exception was:
KeyError: 'metric_file'
"

How to solve it?

**Comment by viktor-begun** [comment]
I solved it. The problem was that "prophet" was not properly installed. I tried to install it from jupyter notebook, but the installation did not work properly. Since I work on Windows in Anaconda, the solution was to run Anaconda Prompt and install prophet with this command "conda install -c conda-forge prophet". Now kats_101 works.
