### ISSUE TITLE
Kats installation failure

### ISSUE THREAD

**Issue by yannmean** [facebookresearch/Kats#317]
Hi, I have been trying for more than a day now, the installation fails all the time when I try to install Kats 3.10.12, I have also tried the minimal installation, but also failed. The error message is not super informative to me, any insights are highly appreciated! Thank you.

Requirement already satisfied: pip in /usr/local/lib/python3.10/dist-packages (23.1.2)
Collecting kats
  Using cached kats-0.2.0-py3-none-any.whl (612 kB)
Requirement already satisfied: attrs>=21.2.0 in /usr/local/lib/python3.10/dist-packages (from kats) (23.1.0)
Collecting deprecated>=1.2.12 (from kats)
  Using cached Deprecated-1.2.14-py2.py3-none-any.whl (9.6 kB)
Requirement already satisfied: matplotlib>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from kats) (3.7.1)
Collecting numpy<1.22,>=1.21 (from kats)
  Using cached numpy-1.21.6-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (15.9 MB)
Collecting pandas<=1.3.5,>=1.0.4 (from kats)
  Using cached pandas-1.3.5-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.5 MB)
Requirement already satisfied: python-dateutil>=2.8.0 in /usr/local/lib/python3.10/dist-packages (from kats) (2.8.2)
Collecting pystan==2.19.1.1 (from kats)
  Using cached pystan-2.19.1.1.tar.gz (16.2 MB)
  Preparing metadata (setup.py) ... done
Collecting fbprophet==0.7.1 (from kats)
  Using cached fbprophet-0.7.1.tar.gz (64 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: scikit-learn>=0.24.2 in /usr/local/lib/python3.10/dist-packages (from kats) (1.2.2)
Collecting scipy<1.8.0 (from kats)
  Using cached scipy-1.7.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (39.9 MB)
Requirement already satisfied: seaborn>=0.11.1 in /usr/local/lib/python3.10/dist-packages (from kats) (0.12.2)
Collecting setuptools-git>=1.2 (from kats)
  Using cached setuptools_git-1.2-py2.py3-none-any.whl (10 kB)
Collecting statsmodels==0.12.2 (from kats)
  Using cached statsmodels-0.12.2.tar.gz (17.5 MB)
  error: subprocess-exited-with-error
  
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Installing build dependencies ... error
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by ma3mool** [comment]
I am running into similar issues, and just wanted to bump this up for a solution.

**Comment by ornatecaesar** [comment]
I'm also getting this error:

Collecting kats
  Using cached kats-0.2.0-py3-none-any.whl (612 kB)
Requirement already satisfied: attrs>=21.2.0 in /Users/davidlawson/PycharmProjects/Python-for-Finance-Cookbook-2E/venv/lib/python3.11/site-packages (from kats) (23.1.0)
Requirement already satisfied: deprecated>=1.2.12 in /Users/davidlawson/PycharmProjects/Python-for-Finance-Cookbook-2E/venv/lib/python3.11/site-packages (from kats) (1.2.14)
Requirement already satisfied: matplotlib>=2.0.0 in /Users/davidlawson/PycharmProjects/Python-for-Finance-Cookbook-2E/venv/lib/python3.11/site-packages (from kats) (3.7.2)
Collecting numpy<1.22,>=1.21 (from kats)
  Using cached numpy-1.21.1.zip (10.3 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting pandas<=1.3.5,>=1.0.4 (from kats)
  Using cached pandas-1.3.5.tar.gz (4.7 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: python-dateutil>=2.8.0 in /Users/davidlawson/PycharmProjects/Python-for-Finance-Cookbook-2E/venv/lib/python3.11/site-packages (from kats) (2.8.2)
Collecting pystan==2.19.1.1 (from kats)
  Using cached pystan-2.19.1.1.tar.gz (16.2 MB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting fbprophet==0.7.1 (from kats)
  Using cached fbprophet-0.7.1.tar.gz (64 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: scikit-learn>=0.24.2 in /Users/davidlawson/PycharmProjects/Python-for-Finance-Cookbook-2E/venv/lib/python3.11/site-packages (from kats) (1.3.0)
Collecting scipy<1.8.0 (from kats)
  Using cached scipy-1.6.1.tar.gz (27.3 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'error'

  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [119 lines of output]
      setup.py:461: UserWarning: Unrecognized setuptools command ('dist_info --egg-base /private/var/folders/gw/pw3z5_pj7m94j3535v1c8d000000gn/T/pip-modern-metadata-cbp58aac'), proceeding with generating Cython sources and expanding templates
        warnings.warn("Unrecognized setuptools command ('{}'), proceeding with "
      setup.py:563: DeprecationWarning:
      
        `numpy.distutils` is deprecated since NumPy 1.23.0, as a result
        of the deprecation of `distutils` itself. It will be removed for
        Python >= 3.12. For older Python versions it will remain present.
        It is recommended to use `setuptools < 60.0` for those Python versions.
        For more details, see:
          https://numpy.org/devdocs/reference/distutils_status_migration.html
      
      
        from numpy.distutils.core import setup
      Running from SciPy source directory.
      INFO: lapack_opt_info:
      INFO: lapack_armpl_info:
      INFO: customize UnixCCompiler
      INFO:   libraries armpl_lp64_mp not found in ['/Users/davidlawson/PycharmProjects/Python-for-Finance-Cookbook-2E/venv/lib', '/usr/lib']
      INFO:   NOT AVAILABLE
      INFO:
      INFO: lapack_mkl_info:
      INFO:   libraries mkl_rt not found in ['/Users/davidlawson/PycharmProjects/Python-for-Finance-Cookbook-2E/venv/lib', '/usr/lib']
      INFO:   NOT AVAILABLE
      INFO:
      INFO: lapack_ssl2_info:
      INFO:   libraries fjlapackexsve not found in ['/Users/davidlawson/PycharmProjects/Python-for-Finance-Cookbook-2E/venv/lib', '/usr/lib']
      INFO:   NOT AVAILABLE
      INFO:
      INFO: openblas_lapack_info:
      INFO:   libraries openblas not found in ['/Users/davidlawson/PycharmProjects/Python-for-Finance-Cookbook-2E/venv/lib', '/usr/lib']
      INFO:   NOT AVAILABLE
      INFO:
      INFO: openblas_clapack_info:
      INFO:   libraries openblas,lapack not found in ['/Users/davidlawson/PycharmProjects/Python-for-Finance-Cookbook-2E/venv/lib', '/usr/lib']
      INFO:   NOT AVAILABLE
      INFO:
      INFO: flame_info:
      INFO:   libraries flame not found in ['/Users/davidlawson/PycharmProjects/Python-for-Finance-Cookbook-2E/venv/lib', '/usr/lib']
      INFO:   NOT AVAILABLE
      INFO:
      INFO: accelerate_info:
      INFO:   NOT AVAILABLE
      INFO:
      INFO: atlas_3_10_threads_info:
      INFO: Setting PTATLAS=ATLAS
      INFO:   libraries tatlas,tatlas not found in /Users/davidlawson/PycharmProjects/Python-for-Finance-Cookbook-2E/venv/lib
      INFO:   libraries tatlas,tatlas not found in /usr/lib
      INFO: <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
      INFO:   NOT AVAILABLE
      INFO:
      INFO: atlas_3_10_info:
      INFO:   libraries satlas,satlas not found in /Users/davidlawson/PycharmProjects/Python-for-Finance-Cookbook-2E/venv/lib
      INFO:   libraries satlas,satlas not found in /usr/lib
      INFO: <class 'numpy.distutils.system_info.atlas_3_10_info'>
      INFO:   NOT AVAILABLE
      INFO:
      INFO: atlas_threads_info:
      INFO: Setting PTATLAS=ATLAS
      INFO:   libraries ptf77blas,ptcblas,atlas not found in /Users/davidlawson/PycharmProjects/Python-for-Finance-Cookbook-2E/venv/lib
      INFO:   libraries ptf77blas,ptcblas,atlas not found in /usr/lib
      INFO: <class 'numpy.distutils.system_info.atlas_threads_info'>
      INFO:   NOT AVAILABLE
      INFO:
      INFO: atlas_info:
      INFO:   libraries f77blas,cblas,atlas not found in /Users/davidlawson/PycharmProjects/Python-for-Finance-Cookbook-2E/venv/lib
      INFO:   libraries f77blas,cblas,atlas not found in /usr/lib
      INFO: <class 'numpy.distutils.system_info.atlas_info'>
      INFO:   NOT AVAILABLE
      INFO:
      INFO: lapack_info:
      INFO:   libraries lapack not found in ['/Users/davidlawson/PycharmProjects/Python-for-Finance-Cookbook-2E/venv/lib', '/usr/lib']
      INFO:   NOT AVAILABLE
      INFO:
      /private/var/folders/gw/pw3z5_pj7m94j3535v1c8d000000gn/T/pip-build-env-ac7hx164/overlay/lib/python3.11/site-packages/numpy/distutils/system_info.py:1972: UserWarning:
          Lapack (http://www.netlib.org/lapack/) libraries not found.
          Directories to search for the libraries can be specified in the
          numpy/distutils/site.cfg file (section [lapack]) or by setting
          the LAPACK environment variable.
        return getattr(self, '_calc_info_{}'.format(name))()
      INFO: lapack_src_info:
      INFO:   NOT AVAILABLE
      INFO:
      /private/var/folders/gw/pw3z5_pj7m94j3535v1c8d000000gn/T/pip-build-env-ac7hx164/overlay/lib/python3.11/site-packages/numpy/distutils/system_info.py:1972: UserWarning:
          Lapack (http://www.netlib.org/lapack/) sources not found.
          Directories to search for the sources can be specified in the
          numpy/distutils/site.cfg file (section [lapack_src]) or by setting
          the LAPACK_SRC environment variable.
        return getattr(self, '_calc_info_{}'.format(name))()
      INFO:   NOT AVAILABLE
      INFO:
      Traceback (most recent call last):
        File "/Users/davidlawson/PycharmProjects/Python-for-Finance-Cookbook-2E/venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/davidlawson/PycharmProjects/Python-for-Finance-Cookbook-2E/venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/davidlawson/PycharmProjects/Python-for-Finance-Cookbook-2E/venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/gw/pw3z5_pj7m94j3535v1c8d000000gn/T/pip-build-env-ac7hx164/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 161, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/private/var/folders/gw/pw3z5_pj7m94j3535v1c8d000000gn/T/pip-build-env-ac7hx164/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 254, in run_setup
          self).run_setup(setup_script=setup_script)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/gw/pw3z5_pj7m94j3535v1c8d000000gn/T/pip-build-env-ac7hx164/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 145, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 588, in <module>
          setup_package()
        File "setup.py", line 584, in setup_package
          setup(**metadata)
        File "/private/var/folders/gw/pw3z5_pj7m94j3535v1c8d000000gn/T/pip-build-env-ac7hx164/overlay/lib/python3.11/site-packages/numpy/distutils/core.py", line 135, in setup
          config = configuration()
                   ^^^^^^^^^^^^^^^
        File "setup.py", line 499, in configuration
          raise NotFoundError(msg)
      numpy.distutils.system_info.NotFoundError: No BLAS/LAPACK libraries found. Note: Accelerate is no longer supported.
      To build Scipy from sources, BLAS & LAPACK libraries need to be installed.
      See site.cfg.example in the Scipy source directory and
      https://docs.scipy.org/doc/scipy/reference/building/index.html for details.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by SonuKumari1690** [comment]
Did anyone for it correct, I am trying it too on Windows platform and python 3.8 but ending up on the same error, as suggested on other issues, installed below libraries still no luck
# !pip install numpy
# !pip install pandas
# !pip install convertdate
# !pip install lunarcalendar
# !pip install holidays==0.23
# !pip install tqdm

**Comment by swimmingCreative** [comment]
I noticed the kats-0.2.0 is developed with python 3.7 and python3.8. But even I use a python version 3.8.11，I still meet a few of problem.

**Comment by carusyte** [comment]
bumping for attention, encountered same issue. Python 3.12.2

**Comment by anjed-gilion** [comment]
I have the same issue, can't go back to 3.8!

**Comment by RYucel** [comment]
Not posibble to install it on Google Colab too. Same problem and output occurs.

**Comment by gomlfx** [comment]
You guys still trying to mess with that? 🤣 Wasting your time.
