### ISSUE TITLE
pip install error for kats 0.2.0

### ISSUE THREAD

**Issue by Shishykish** [facebookresearch/Kats#324]
Hello, 

I have the following environment
Anaconda - latest
Python - latest

I will use pip install kats in the usual way. Then I get the following error. 

`Collecting pystan==2.19.1.1 (from kats==0.2.0)
  Using cached pystan-2.19.1.1.tar.gz (16.2 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Kishan\AppData\Local\Temp\pip-install-l2gn3u7j\pystan_4e87c29debc5432ab5b3a78dddb4be13\setup.py", line 122, in <module>
          from Cython.Build.Inline import _get_build_extension
      ModuleNotFoundError: No module named 'Cython'
      [end of output]`

Can anyone offer some suggestions? or tell me where else to look.

**Comment by nistrup** [comment]
I had the same issue using Python 3.10, I tired rolling back to 3.9, same issue, **finally rolled back to 3.7 and it fixed the issue.**
